### ISSUE TITLE
Column class's sql function return value shoud contains column.note

### ISSUE THREAD

**Issue by me-drinks** [Vanderhoof/PyDBML#1]
https://github.com/Vanderhoof/PyDBML/blob/e09b05a969af7874e0cf5a17c549c986821f01b1/pydbml/classes.py#L293
sql function's return value shoud contains column.note

`   @property
    def sql(self):
        '''
        Returns inline SQL of the column, which should be a part of table definition:
        "id" integer PRIMARY KEY AUTOINCREMENT
        '''
        self.check_attributes_for_sql()
        components = [f'"{self.name}"', str(self.type)]
        if self.pk:
            components.append('PRIMARY KEY')
        if self.autoinc:
            components.append('AUTOINCREMENT')
        if self.unique:
            components.append('UNIQUE')
        if self.not_null:
            components.append('NOT NULL')
        if self.default is not None:
            components.append('DEFAULT ' + str(self.default))
        if self.note is not None:    # add this line 
            components.append('Comment' + str(self.note))
        return ' '.join(components)
`

**Comment by Vanderhoof** [comment]
Hi @me-drinks!
You mean insert notes as SQL comments? That's a nice idea

**Comment by Vanderhoof** [comment]
Done in 0.3.4
