### ISSUE TITLE
Project Note renders malformed dbml

### ISSUE THREAD

**Issue by jens-koster** [Vanderhoof/PyDBML#15]
parse the below as a file, the db.dbml property corrupts the format by  putting curly braces around the note. 
Project DocDWH {
  database_type: 'BigQuery'
  Note: '''
    # document related tables
    **markdown content here**
  '''
}

turns into the below in the dbml-property:
Project DocDWH {
  database_type: 'BigQuery'
  Note: {'''
    # document related tables
    **markdown content here**
  '''}
}

this will not load again in pydbml due to the curly braces (or on dbdiagram.io)
I fixed it in note.py, it is just a question of removing the curly braces form the output in the dbml property. Didn't think to make a pull request before changing a lot more stuff in my fork, sorry about that!

**Comment by Vanderhoof** [comment]
Thanks for finding this! I'll fix this in the next version
