### ISSUE TITLE
Convert SQLAlchemy model or DDL into DBMl

### ISSUE THREAD

**Issue by romanzdk** [Vanderhoof/PyDBML#29]
Hello, love your project.

Is it somehow possible to convert SQLAlchemy project into DBML? Or even SQL DDL statements into the DBML?

Thank you!

**Comment by Vanderhoof** [comment]
Hey! You can convert SQL into DBML using the [official tool](https://dbml.dbdiagram.io/cli/#convert-a-sql-file-to-dbml). Never tried it, so can't confirm if it's good or not : )
