### ISSUE TITLE
Arrays are not supported

### ISSUE THREAD

**Issue by aviallon** [Vanderhoof/PyDBML#4]
Specifying `varchar[]` as a column type doesn't work and results in a syntax error. It is however supported by the most major DBML tool currently available (dbdiagram), and is thus used in many shemas.
Perhaps adding it would be nice?

**Comment by aviallon** [comment]
Never mind, it seems that dbdiagram allows some flexibility over the specification, which states that array types are to be enclosed in quotes, like so `"varchar[]"`.

**Comment by Vanderhoof** [comment]
Yes, quoted `"varchar[]"` seems to work fine
