### ISSUE TITLE
Writing Changes to Parsed DBML

### ISSUE THREAD

**Issue by bt-kvaghmare** [Vanderhoof/PyDBML#5]
Hi.

**Thanks so much for a wonderful library to read and understand DBML files.**

I was wondering what would it take to achieve the following:

- Read a DBML file and parse it.
- Change the contents, like notes for example.
- And rewrite changes to DBML.

I believe the first two are easy. It's the third that needs some thinking. Looking to hear from you.

**Comment by Vanderhoof** [comment]
Hi!

You mean apart from being able to output to SQL, PyDBML should be able to output back to DBML? That's a quite reasonable thing to do, I'll plan it for development in nearest future

Thank you for the idea!

**Comment by bt-kvaghmare** [comment]
Thanks for the quick response!

Yes! That's exactly what I had in mind! Once the library becomes two way - DBML to Python object and Python object to DBML - there are many other future possibilities that could open up, I think.

**Comment by Vanderhoof** [comment]
@bt-kvaghmare Please check the latest release [0.4.1](https://github.com/Vanderhoof/PyDBML/releases/tag/0.4.1), now exporting to DBML is available via `dbml` attribute in parsed results class, as well in most classes separately.

PyDBML is still not very suitable for building DBML schema in Python from scratch, but that is the plan for further releases.

Please tell me if it works. I've tested the new features thoroughly, but you know how it happens sometimes : }

**Comment by bt-kvaghmare** [comment]
Thanks for this! I shall give it a spin and let you know. And sorry for the late response.

**Comment by bt-kvaghmare** [comment]
@Vanderhoof, it worked! If I load the DBML file as an object `parsed` and then modify a few things, like adding notes for example, `parsed.dbml` gets updated to show the changes. It should be trivial to output to string into a file with the same or modified name.
